"""Public, framework-neutral API for the YouTube clipper pipeline."""

from .application.pipeline import ClipPipeline
from .config import (
    DEFAULT_ANALYSIS_MODEL,
    ContentType,
    LLMProvider,
    resolve_analysis_model,
)
from .domain.errors import (
    AnalysisError,
    ClipperError,
    DependencyError,
    DownloadError,
    DurationLimitError,
    InsufficientHighlightsError,
    MediaExtractionError,
    MediaProbeError,
    RenderError,
    SourceTransferError,
    TranscriptError,
)
from .domain.models import (
    ClipCandidate,
    HighlightMoment,
    HighlightMontage,
    PipelineConfig,
    PipelineEvent,
    PipelineResult,
    PipelineStage,
    ProgressCallback,
    TranscriptDocument,
    TranscriptMode,
    TranscriptOrigin,
    VideoLayout,
    VideoMetadata,
    WhisperDevice,
)

__all__ = [
    "DEFAULT_ANALYSIS_MODEL",
    "AnalysisError",
    "ClipCandidate",
    "ClipPipeline",
    "ClipperError",
    "ContentType",
    "HighlightMoment",
    "HighlightMontage",
    "DependencyError",
    "DownloadError",
    "DurationLimitError",
    "InsufficientHighlightsError",
    "MediaExtractionError",
    "MediaProbeError",
    "LLMProvider",
    "PipelineConfig",
    "PipelineEvent",
    "PipelineResult",
    "PipelineStage",
    "ProgressCallback",
    "RenderError",
    "SourceTransferError",
    "TranscriptDocument",
    "TranscriptError",
    "TranscriptMode",
    "TranscriptOrigin",
    "VideoLayout",
    "VideoMetadata",
    "WhisperDevice",
    "resolve_analysis_model",
]
